// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DrawGrid: typeof import('./src/components/DrawGrid.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}

export { }
